#YandexGPT
api_key: <ВАШ_API_КЛЮЧ>
catalog_id: <ВАШ_ИДЕНТИФИКАТОР_КАТАЛОГА>

#Gigachat
token: <ВАШ_ТОКЕН>'
credentials: <ВАШ_КЛЮЧ_АВТОРИЗАЦИИ>
scope: !!str GIGACHAT_API_PERS
science_dataset_path: !!str <ПУТЬ_ДО_ДАННЫХ_ДАТАСЕТА_science_summarization_dataset>

yandexgpt:
  dialogsum_ru:
  - role: system
    text: "Ты система, которая анализирует и понимает диалоги"
  - role: user
    text: "Сгенерируй краткий пересказ этого диалога в 1-2 предложениях:"
  reviews_russian:
  - role: system
    text: "Ты система, которая анализирует и понимает отзывы на отели и гостиницы"
  - role: user
    text: "Сгенерируй краткий пересказ этого отзыва. Выделяй только важные факты. Отзыв:"
  ru_simple_sent_eval:
  - role: system
    text: "Ты система, которая переписывает текст в более понятной и простой форме"
  - role: user
    text: "Перепиши предложение так, чтобы его стало проще понимать: "
  science_summarization_dataset:
  - role: system
    text: "Ты система, которая анализирует научные статьи и пишет их краткое содержание."
  - role: user
    text: "Ниже приведена научная статья. Выдели главные факты и напиши краткое содержание этой статьи.\n"
  telegram-financial-sentiment-summarization:
  - role: system
    text: "Ты система, которая анализирует новости и пишет краткие пересказы."
  - role: user
    text: "Напиши краткий пересказ этой новости. Выделяй только важные факты. Текст новости: "
  yandex_jobs:
  - role: system
    text: "Ты система, которая анализирует вакансии в сфере IT"
  - role: user
    text: "Напиши название должности для этой вакансии: "

gigachat:
  dialogsum_ru: "Сгенерируй краткий пересказ этого диалога в 1-2 предложениях:"
  reviews_russian: "Сгенерируй краткий пересказ этого отзыва. Выделяй только важные факты. Отзыв:"
  ru_simple_sent_eval: "Перепиши предложение так, чтобы его стало проще понимать: "
  science_summarization_dataset: "Ниже приведена научная статья. Выдели главные факты и напиши краткое содержание этой статьи.\n"
  telegram-financial-sentiment-summarization: "Напиши краткий пересказ этой новости. Выделяй только важные факты. Текст новости: "
  yandex_jobs: "Напиши название должности для этой вакансии: "